import { avatarFor, contactFor, mark } from "./helpers";
import type { SeedFriend } from "./types";

export const FRIENDS: SeedFriend[] = [
  // scenario: ~30d overdue (weekly frequency), linked contact
  {
    first_name: "Alex",
    last_name: mark("Chen"),
    frequency_preset: "weekly",
    frequency_amount: 1,
    frequency_unit: "weeks",
    avatar_url: avatarFor("alex-chen"),
    contact: contactFor({
      id: "seed-contact-alex-chen",
      name: "Alex Chen",
      phone: "+14155550181",
      email: "alex.chen@example.com",
      imageUri: avatarFor("alex-chen"),
      syncedDaysAgo: 30,
    }),
    createdDaysAgo: 200,
    events: [
      {
        offsetDays: -37,
        atHour: 15,
        atMinute: 30,
        status: "completed",
        medium: "text",
        medium_detail: "iMessage",
        location_text: null,
        location_address: null,
        event_notes:
          "Quick check-in. Said the new job is going well but they've been swamped.\n\nWants to do a climbing trip in summer.",
      },
      {
        offsetDays: -70,
        atHour: 19,
        status: "completed",
        medium: "call",
        medium_detail: null,
        location_text: null,
        location_address: null,
        event_notes: null,
      },
    ],
  },
  // scenario: long overdue (weekly frequency) — last completion is months old,
  // and a later cancelled event keeps history without resetting the clock.
  // Linked contact w/o avatar.
  {
    first_name: "Bailey",
    last_name: mark("Park"),
    frequency_preset: "weekly",
    frequency_amount: 1,
    frequency_unit: "weeks",
    avatar_url: null,
    contact: contactFor({
      id: "seed-contact-bailey-park",
      name: "Bailey Park",
      phone: "+16175550144",
      email: "bailey.park@example.com",
      syncedDaysAgo: 90,
    }),
    createdDaysAgo: 365,
    events: [
      {
        offsetDays: -107,
        atHour: 10,
        status: "completed",
        medium: "video",
        medium_detail: "Zoom",
        location_text: null,
        location_address: null,
        event_notes: "Caught up about the move. They love the new place.",
      },
      {
        offsetDays: -40,
        atHour: 12,
        atMinute: 30,
        status: "cancelled",
        medium: null,
        medium_detail: null,
        location_text: null,
        location_address: null,
        event_notes:
          "Cancelled — they had to bail last minute, never rescheduled.",
      },
    ],
  },
  // scenario: 1d overdue (weekly frequency), unlinked
  {
    first_name: "Cam",
    last_name: mark("Rivera"),
    frequency_preset: "weekly",
    frequency_amount: 1,
    frequency_unit: "weeks",
    avatar_url: null,
    contact: null,
    createdDaysAgo: 90,
    events: [
      {
        offsetDays: -8,
        atHour: 9,
        status: "completed",
        medium: "in_person",
        medium_detail: null,
        location_text: "Sightglass",
        location_address: "270 7th St, San Francisco, CA",
        event_notes:
          "Walked through their startup idea. Interesting but very early.",
      },
    ],
  },
  // scenario: 1d overdue (monthly frequency), linked contact
  {
    first_name: "Dana",
    last_name: mark("Wu"),
    frequency_preset: "monthly",
    frequency_amount: 1,
    frequency_unit: "months",
    avatar_url: avatarFor("dana-wu"),
    contact: contactFor({
      id: "seed-contact-dana-wu",
      name: "Dana Wu",
      phone: "+12065550199",
      email: "dana.wu@example.com",
      imageUri: avatarFor("dana-wu"),
      syncedDaysAgo: 60,
    }),
    createdDaysAgo: 120,
    events: [
      {
        offsetDays: -32,
        atHour: 20,
        status: "completed",
        medium: "call",
        medium_detail: null,
        location_text: null,
        location_address: null,
        event_notes: null,
      },
    ],
  },
  // scenario: never caught up (no events), recently linked contact with no
  // email on file — exercises the disabled Email action button.
  {
    first_name: "Eli",
    last_name: mark("Brooks"),
    frequency_preset: "monthly",
    frequency_amount: 1,
    frequency_unit: "months",
    avatar_url: null,
    contact: contactFor({
      id: "seed-contact-eli-brooks",
      name: "Eli Brooks",
      phone: "+13105550172",
      email: null,
      syncedDaysAgo: 5,
    }),
    createdDaysAgo: 60,
    events: [],
  },
  // scenario: scheduled today (was due), upcoming reminder fires shortly before
  {
    first_name: "Faye",
    last_name: mark("Holloway"),
    frequency_preset: "weekly",
    frequency_amount: 1,
    frequency_unit: "weeks",
    avatar_url: avatarFor("faye-holloway"),
    contact: contactFor({
      id: "seed-contact-faye-holloway",
      name: "Faye Holloway",
      phone: "+19175550127",
      email: "faye.holloway@example.com",
      imageUri: avatarFor("faye-holloway"),
      syncedDaysAgo: 14,
    }),
    createdDaysAgo: 40,
    events: [
      {
        offsetDays: -6,
        atHour: 22,
        status: "completed",
        medium: "text",
        medium_detail: null,
        location_text: null,
        location_address: null,
        event_notes: "Short chat — they were on the way out.",
      },
      {
        offsetDays: 0,
        atHour: 19,
        status: "scheduled",
        medium: "video",
        medium_detail: "FaceTime",
        location_text: null,
        location_address: null,
        event_notes: "Planning to catch up about their new role.",
        pre_reminder_minutes: 30,
      },
    ],
  },
  // scenario: due in 3 weeks, exercises a long hyphenated last name for layout
  // and includes a prior-year completed event to exercise the year-on-history-date display
  {
    first_name: "Gabriella",
    last_name: mark("Constantinopoulos-Whitfield"),
    frequency_preset: "monthly",
    frequency_amount: 1,
    frequency_unit: "months",
    avatar_url: null,
    contact: null,
    createdDaysAgo: 400,
    events: [
      {
        offsetDays: -7,
        atHour: 21,
        status: "completed",
        medium: "video",
        medium_detail: "Whatsapp",
        location_text: null,
        location_address: null,
        event_notes: "She's planning to visit in the fall.",
      },
      {
        offsetDays: -45,
        atHour: 20,
        status: "cancelled",
        medium: "video",
        medium_detail: null,
        location_text: null,
        location_address: null,
        event_notes:
          "Cancelled — she had a work emergency. Rescheduled the week after.",
      },
      {
        offsetDays: -38,
        atHour: 20,
        atMinute: 30,
        status: "completed",
        medium: "video",
        medium_detail: "Whatsapp",
        location_text: null,
        location_address: null,
        event_notes: null,
      },
      {
        offsetDays: -220,
        atHour: 18,
        status: "completed",
        medium: "in_person",
        medium_detail: null,
        location_text: "Her parents' place",
        location_address: "Pasadena, CA",
        event_notes:
          "She was back stateside for the holidays. Long catch-up over wine.",
      },
      {
        offsetDays: 20,
        atHour: 21,
        status: "scheduled",
        medium: "video",
        medium_detail: "Whatsapp",
        location_text: null,
        location_address: null,
        event_notes: "Pencilled in to plan her fall trip in detail.",
        pre_reminder_minutes: 60,
      },
    ],
  },
  // scenario: caught up 2d ago (6-month frequency, not due), linked contact
  {
    first_name: "Harper",
    last_name: mark("Singh"),
    frequency_preset: "6_months",
    frequency_amount: 6,
    frequency_unit: "months",
    avatar_url: avatarFor("harper-singh"),
    contact: contactFor({
      id: "seed-contact-harper-singh",
      name: "Harper Singh",
      phone: "+14085550113",
      email: "harper.singh@example.com",
      imageUri: avatarFor("harper-singh"),
      syncedDaysAgo: 45,
    }),
    createdDaysAgo: 200,
    events: [
      {
        offsetDays: -2,
        atHour: 19,
        atMinute: 30,
        status: "completed",
        medium: "in_person",
        medium_detail: null,
        location_text: "Liholiho Yacht Club",
        location_address: "871 Sutter St, San Francisco, CA",
        event_notes:
          "Long catch-up — talked about the move, the new job, and their plans for the next year. Going to introduce me to their friend Sasha who's also in design.",
      },
      {
        offsetDays: 14,
        atHour: 12,
        atMinute: 30,
        status: "scheduled",
        medium: "in_person",
        medium_detail: null,
        location_text: "Tartine Bakery",
        location_address: "600 Guerrero St, San Francisco, CA",
        event_notes: "Tentative lunch — they want to introduce me to Sasha.",
        pre_reminder_minutes: 60,
      },
    ],
  },
  // scenario: no frequency set, unlinked
  {
    first_name: "Indra",
    last_name: mark("Olamide"),
    frequency_preset: null,
    frequency_amount: null,
    frequency_unit: null,
    avatar_url: null,
    contact: null,
    createdDaysAgo: 90,
    events: [
      {
        offsetDays: -14,
        atHour: 11,
        status: "completed",
        medium: "text",
        medium_detail: null,
        location_text: null,
        location_address: null,
        event_notes: null,
      },
      {
        offsetDays: 6,
        atHour: 18,
        status: "scheduled",
        medium: "call",
        medium_detail: null,
        location_text: null,
        location_address: null,
        event_notes: "Open-ended catch-up call.",
        pre_reminder_minutes: 30,
      },
    ],
  },
  // scenario: scheduled event 2d in the past — awaiting follow-up (complete / reschedule / cancel)
  {
    first_name: "Kai",
    last_name: mark("Nakamura"),
    frequency_preset: "monthly",
    frequency_amount: 1,
    frequency_unit: "months",
    avatar_url: avatarFor("kai-nakamura"),
    contact: contactFor({
      id: "seed-contact-kai-nakamura",
      name: "Kai Nakamura",
      phone: "+12135550168",
      email: "kai.nakamura@example.com",
      imageUri: avatarFor("kai-nakamura"),
      syncedDaysAgo: 20,
    }),
    createdDaysAgo: 150,
    events: [
      {
        offsetDays: -34,
        atHour: 18,
        atMinute: 30,
        status: "completed",
        medium: "call",
        medium_detail: null,
        location_text: null,
        location_address: null,
        event_notes: "Talked about their team change. Sounds promising.",
      },
      {
        offsetDays: -2,
        atHour: 8,
        atMinute: 30,
        status: "scheduled",
        medium: "in_person",
        medium_detail: null,
        location_text: "Blue Bottle",
        location_address: "66 Mint St, San Francisco, CA",
        event_notes: "Coffee before their flight out.",
        pre_reminder_minutes: 60,
      },
    ],
  },
  // scenario: not yet due (monthly frequency) with a recent cancelled event —
  // a cancellation keeps history but doesn't change the friend's state, so
  // they stay "On track" until frequency says otherwise.
  {
    first_name: "Marlowe",
    last_name: mark("Quinn"),
    frequency_preset: "monthly",
    frequency_amount: 1,
    frequency_unit: "months",
    avatar_url: avatarFor("marlowe-quinn"),
    contact: contactFor({
      id: "seed-contact-marlowe-quinn",
      name: "Marlowe Quinn",
      phone: "+15035550136",
      email: "marlowe.quinn@example.com",
      imageUri: avatarFor("marlowe-quinn"),
      syncedDaysAgo: 25,
    }),
    createdDaysAgo: 180,
    events: [
      {
        offsetDays: -15,
        atHour: 19,
        status: "completed",
        medium: "call",
        medium_detail: null,
        location_text: null,
        location_address: null,
        event_notes:
          "Short catch-up — agreed to grab coffee in a couple weeks.",
      },
      {
        offsetDays: -3,
        atHour: 10,
        status: "cancelled",
        medium: "in_person",
        medium_detail: null,
        location_text: "Ritual Coffee",
        location_address: "1026 Valencia St, San Francisco, CA",
        event_notes: "They had to bail last minute. Never rescheduled.",
      },
    ],
  },
  // scenario: 3d overdue, long hyphenated last name for layout, scheduled event w/ day-ahead reminder
  {
    first_name: "Jules",
    last_name: mark("Marchetti-Andersen"),
    frequency_preset: "weekly",
    frequency_amount: 1,
    frequency_unit: "weeks",
    avatar_url: avatarFor("jules-marchetti"),
    contact: null,
    createdDaysAgo: 90,
    events: [
      {
        offsetDays: -10,
        atHour: 18,
        atMinute: 30,
        status: "completed",
        medium: "call",
        medium_detail: null,
        location_text: null,
        location_address: null,
        event_notes: "They were driving — kept it short.",
      },
      {
        offsetDays: 3,
        atHour: 12,
        status: "scheduled",
        medium: "in_person",
        medium_detail: null,
        location_text: "Tartine Manufactory",
        location_address: "595 Alabama St, San Francisco, CA",
        event_notes: null,
        pre_reminder_minutes: 1440,
      },
    ],
  },
  // scenario: calendar multi-dot coverage — events land on days that already
  // contain other friends' events to exercise the two-status day markers
  // (day -7 pairs scheduled with Gabriella's completed; day -2 pairs
  // completed with Kai's scheduled).
  {
    first_name: "Noor",
    last_name: mark("Reyes"),
    frequency_preset: "weekly",
    frequency_amount: 1,
    frequency_unit: "weeks",
    avatar_url: null,
    contact: null,
    createdDaysAgo: 45,
    events: [
      {
        offsetDays: -7,
        atHour: 14,
        status: "scheduled",
        medium: "call",
        medium_detail: null,
        location_text: null,
        location_address: null,
        event_notes:
          "Phone catch-up — never connected, still need to follow up.",
      },
      {
        offsetDays: -2,
        atHour: 11,
        status: "completed",
        medium: "in_person",
        medium_detail: null,
        location_text: "Andytown Coffee",
        location_address: "3655 Lawton St, San Francisco, CA",
        event_notes: "Quick coffee — kept it short since their kid was sick.",
      },
    ],
  },
];
